1.intrinsic_knowledge:
    event_in_topic: /task_planning/upload_pddl_knowledge_node/event_in
    event_in_strings: [e_start]
    event_out_topic: /task_planning/upload_pddl_knowledge_node/event_out
2.check_unfinished_goals:
    event_in_topic: /task_planning/knowledge_base_analyzer_node/pending_goals/event_in
    event_in_strings: [e_start]
    event_out_topic: /task_planning/knowledge_base_analyzer_node/pending_goals/event_out
3.check_new_knowledge:
    event_in_topic: /task_planning/knowledge_base_analyzer_node/new_knowledge/event_in
    event_in_strings: [e_start]
    event_out_topic: /task_planning/knowledge_base_analyzer_node/new_knowledge/event_out
4.generate_pddl_problem:
    event_in_topic: /task_planning/pddl_problem_generator_node/event_in
    event_in_strings: [e_start]
    event_out_topic: /task_planning/pddl_problem_generator_node/event_out
5.make_plan:
    event_in_topic: /task_planning/mercury_planner/event_in
    event_in_strings: [e_start]
    event_out_topic: /task_planning/mercury_planner/event_out
6.analyse_plan_success:
    event_in_topic: /task_planning/plan_success_analizer/event_in
    event_in_strings: [e_start]
    event_out_topic: /task_planning/plan_success_analizer/event_out
7.dispatch_and_executor:
    event_in_topic: /task_planning/plan_parse_dispatch_node/event_in
    event_in_strings: [e_start]
    event_out_topic: /task_planning/plan_parse_dispatch_node/event_out
